In [7]:
import pandas as pd
import numpy as np

from statsmodels.formula.api import ols
from statsmodels.iolib.summary2 import summary_col, summary_params # вывод результатов тестирования
from scipy.stats import t # t-распределение и критические значения
from scipy.stats import f # f-распределение и критические значения

# Не показывать Warnings
import warnings
warnings.simplefilter(action='ignore', category=Warning)

# 2.1

## 2.1.1

In [8]:
# импорт данных
df = pd.read_csv('sleep75.csv')

In [13]:
# спецификация модели
mod = ols(formula='sleep~totwrk+age+male+south+smsa+yngkid+marr+union', data=df)
# подгонка модели с ковариационной матрицей по умолчанию (неробастной)
res_ols = mod.fit()
# уровень значимости
sign_level = 0.1
# критическое значение t-распределения
t.ppf(q=1-sign_level/2, df=mod.df_resid)

np.float64(1.6470427356548243)

In [14]:
summary_params(res_ols, alpha=0.05).round(3)

              Coef.  Std.Err.       t  P>|t|    [0.025    0.975]
Intercept  3446.830    81.840  42.117  0.000  3286.148  3607.513
totwrk       -0.169     0.018  -9.358  0.000    -0.205    -0.134
age           2.714     1.472   1.844  0.066    -0.176     5.605
male         87.108    35.173   2.477  0.014    18.050   156.166
south       102.272    41.925   2.439  0.015    19.957   184.586
smsa        -54.188    33.193  -1.632  0.103  -119.359    10.983
yngkid      -13.051    50.459  -0.259  0.796  -112.121    86.019
marr         31.360    42.263   0.742  0.458   -51.618   114.339
union        11.866    38.186   0.311  0.756   -63.107    86.839

In [15]:
res_ols.pvalues.round(4)

Intercept    0.0000
totwrk       0.0000
age          0.0657
male         0.0135
south        0.0150
smsa         0.1030
yngkid       0.7960
marr         0.4583
union        0.7561
dtype: float64

In [16]:
F_test = res_ols.f_test('smsa=yngkid=marr=union=0')
print(F_test)

<F test: F=0.9097649568071097, p=0.4576805992248939, df_denom=697, df_num=4>

In [17]:
# уровень значимости
sign_level = 0.05
# Критическое значение F-распределения
f.ppf(q=1-sign_level, dfn=F_test.df_num, dfd=F_test.df_denom)

np.float64(2.3847110483450447)

F < Fcr поэтому незначимо

## 2.2

In [19]:
# спецификация модели
mod = ols(formula='sleep~totwrk+age+I(age**2)+male+south', data=df)
# подгонка модели с ковариационной матрицей по умолчанию (неробастной)
res_ols = mod.fit()
# уровень значимости
sign_level = 0.01
# критическое значение t-распределения
t.ppf(q=1-sign_level/2, df=mod.df_resid)

np.float64(2.5828710085584943)

In [45]:
summary_params(res_ols, alpha=0.01).round(3)

             Coef.  Std.Err.      t  P>|t|  [0.005  0.995]
Intercept    2.938     1.656  1.774  0.076  -1.337   7.213
age          0.145     0.100  1.447  0.148  -0.113   0.403
I(age ** 2) -0.002     0.002 -1.236  0.217  -0.006   0.002
IQ           0.008     0.001  9.770  0.000   0.006   0.010
south       -0.100     0.027 -3.736  0.000  -0.170  -0.031
urban        0.173     0.028  6.260  0.000   0.102   0.245
married      0.202     0.040  5.008  0.000   0.098   0.305

### 2.2.1

значимы totwrk, male, south т.к. у них |t| > tcr

In [46]:
F_test = res_ols.f_test('age=I(age ** 2)=0')
print(F_test)

<F test: F=14.832640139579382, p=4.5612557062812974e-07, df_denom=928, df_num=2>

In [47]:
# уровень значимости
sign_level = 0.01
# Критическое значение F-распределения
f.ppf(q=1-sign_level, dfn=F_test.df_num, dfd=F_test.df_denom)

np.float64(4.628098987933653)

Незначимы т.к. Fcr > F: 3>2.35

### 2.2.2

In [26]:
res_hc = mod.fit(cov_type='HC3')
# альтернативная спецификация тестируемой гипотезы
F_test = res_hc.f_test('age=I(age ** 2)=0')
print(F_test)

<F test: F=2.908392017528972, p=0.05522306187651156, df_denom=700, df_num=2>

In [27]:
# Тестовая статистика и её P-значение
F_test.statistic, F_test.pvalue

(2.908392017528972, np.float64(0.05522306187651156))

In [28]:
# уровень значимости
sign_level = 0.05
# Критическое значение F-распределения
f.isf(q=sign_level, dfn=F_test.df_num, dfd=F_test.df_denom)

np.float64(3.0085895184656937)

Незначимо т.к. Fcr > F: 3 > 2.91

# 2.3

In [31]:
# спецификация модели
mod = ols(formula='sleep~totwrk+age+I(age**2)+male+south+totwrk:male', data=df)
# подгонка модели с ковариационной матрицей по умолчанию (неробастной)
res_ols = mod.fit()
# уровень значимости
sign_level = 0.01
# критическое значение t-распределения
t.ppf(q=1-sign_level/2, df=mod.df_resid)

np.float64(2.582881108461278)

In [32]:
summary_params(res_ols, alpha=0.01).round(3)

                Coef.  Std.Err.       t  P>|t|    [0.005    0.995]
Intercept    3587.178   220.238  16.288  0.000  3018.329  4156.028
totwrk         -0.149     0.026  -5.673  0.000    -0.217    -0.081
age            -6.259    11.192  -0.559  0.576   -35.166    22.649
I(age ** 2)     0.107     0.134   0.796  0.426    -0.239     0.452
male          161.890    82.177   1.970  0.049   -50.365   374.145
south         112.144    40.717   2.754  0.006     6.976   217.312
totwrk:male    -0.035     0.036  -0.956  0.339    -0.128     0.059

totwrk и south незначимы ибо |t|>tcr

In [33]:
F_test = res_ols.f_test('male=totwrk:male=0')
print(F_test)

<F test: F=3.943030040676654, p=0.01982218606004991, df_denom=699, df_num=2>

In [34]:
# Критическое значение F-распределения
f.isf(q=sign_level, dfn=F_test.df_num, dfd=F_test.df_denom)

np.float64(4.635643786895793)

Незначимо т.к. Fcr > F: 4.64 > 3.94

# 2.4

In [36]:
# импорт данных
df = pd.read_csv('wage2.csv')

In [52]:
# спецификация модели
mod = ols(formula='np.log(wage)~age+I(age**2)+IQ+south+urban+married', data=df)
# подгонка модели с ковариационной матрицей по умолчанию (неробастной)
res_ols = mod.fit()
# уровень значимости
sign_level = 0.01
# критическое значение t-распределения
t.ppf(q=1-sign_level/2, df=mod.df_resid)

np.float64(2.5811375814942803)

In [53]:
summary_params(res_ols, alpha=0.01).round(3)

             Coef.  Std.Err.      t  P>|t|  [0.005  0.995]
Intercept    2.938     1.656  1.774  0.076  -1.337   7.213
age          0.145     0.100  1.447  0.148  -0.113   0.403
I(age ** 2) -0.002     0.002 -1.236  0.217  -0.006   0.002
IQ           0.008     0.001  9.770  0.000   0.006   0.010
south       -0.100     0.027 -3.736  0.000  -0.170  -0.031
urban        0.173     0.028  6.260  0.000   0.102   0.245
married      0.202     0.040  5.008  0.000   0.098   0.305

Значимы iq, south, urban, married т.к. |t|>tcr

In [54]:
F_test = res_ols.f_test('age=I(age ** 2)=0')
print(F_test)

<F test: F=14.832640139579382, p=4.5612557062812974e-07, df_denom=928, df_num=2>

In [55]:
# Тестовая статистика и её P-значение
F_test.statistic, F_test.pvalue.round(2)

(14.832640139579382, np.float64(0.0))

In [56]:
# Критическое значение F-распределения
f.isf(q=sign_level, dfn=F_test.df_num, dfd=F_test.df_denom)

np.float64(4.628098987933653)

Значимо т.к. F>Fcr